# Generated by Django 6.1 on 2026-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_replace_partial_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
